#!/bin/bash

# Create the updated package
dotnet pack ./src

if dotnet new -l | grep MassTransit; then
    dotnet new uninstall MassTransit.Templates
fi

dotnet new install ./src/bin/Release/MassTransit.Templates.1.0.7.nupkg